# This file specifies the JVM that will be used to run the Gradle Daemon.
# The Daemon JVM can be specified by version, vendor, or both.
# If no Daemon JVM is specified, the JVM used to run Gradle will be used.
# If a Daemon JVM is specified, Gradle will search for a matching JVM on the local machine
# and download one if no match is found.
# The Daemon JVM specification is used for the current project and any included projects.
# The Daemon JVM specification can be overridden by the GRADLE_DAEMON_JVM_VERSION property
# or the --daemon-jvm-version command line option.
# For more information on the Daemon JVM, see https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:daemon_jvm

toolchainVersion=17
