plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    alias(libs.plugins.apollo.graphql)
}

android {
    compileSdk 37

    namespace "br.com.pokebase"

    defaultConfig {
        applicationId "br.com.pokebase"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
        compose true
    }
}

kotlin {
    jvmToolchain(17)
}

apollo {
    service("service") {
        packageName.set("br.com.pokebase")

        introspection {
            endpointUrl.set("https://graphql.pokeapi.co/v1beta2")
            schemaFile.set(file("src/main/graphql/schema.graphqls"))
        }
    }
}

dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.cardview
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx
    
    // Compose
    implementation platform(libs.androidx.compose.bom)
    androidTestImplementation platform(libs.androidx.compose.bom)

    implementation libs.androidx.ui
    implementation libs.androidx.ui.graphics
    implementation libs.androidx.ui.tooling.preview
    implementation libs.androidx.material3
    implementation libs.androidx.activity.compose
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.androidx.navigation.compose
    implementation libs.hilt.navigation.compose

    // Testing
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    // Hilt
    implementation libs.hilt.android
    ksp libs.hilt.android.compiler
    implementation libs.hilt.navigation.compose
    ksp libs.hilt.compiler

    //Gson
    implementation libs.gson

    // Network
    implementation libs.retrofit
    implementation libs.retrofit.converter.gson
    implementation libs.okhttp.logging.interceptor
    implementation libs.apollo.graphql

    // Coil 3
    implementation platform(libs.coil.bom)
    implementation libs.coil.compose
    implementation libs.coil.network.okhttp

    // Lottie
    implementation libs.lottie.compose
}
